### ISSUE TITLE
Random websocket port on emulator UI

### ISSUE THREAD

**Issue by chrsin** [matthewkrupnik/docker-firestore-emulator-with-ui#11]
Hi Matthew. Awesome image you've made.

Have you found a way around the randomized websocket port?
Might just be me being dense. But the UI doesn't show any data since the websocket call is failing. :(
(My assumption that the failing websocket connection is why there is no data showing in the UI)

**Comment by chrsin** [comment]
Not sure if its possible but maybe using "websocketPort" in firebase.json.
(seen in) https://github.com/firebase/firebase-tools/issues/3837

When I try building your image i get "exec ./entrypoint.sh: no such file or directory" when I run it. So I think I'm doing something wrong. So I can't test if it actually works. :(

**Comment by matthewkrupnik** [comment]
I updated the container to support websocket port and pushed new image to dockerhub. Did a quick test and I can build it, start it and see the UI locally.

**Comment by chrsin** [comment]
That is amazing! The UI works as intended and It updates correctly!
Thanks a bundle! 🥇 

One last thing. It says its running on arm64 architecture.
Would it be possible to support something more windows friendly aswell?
![image](https://user-images.githubusercontent.com/365603/206485575-c20c8b6b-4172-4db9-9dde-656c578fb919.png)
Not sure if the emulator suite is always this memory hungry but its eating 1.5GB and between 2-10% of the CPU.

**Comment by matthewkrupnik** [comment]
ARM64 is because I built it on my MacBook Air with the M1. It used to auto-build from dockerhub, but they don't do that for free anymore. So I need to setup a GitHub Actions pipeline to build and push the image. I'll work on that today.

As for resource utilization, I believe that's normal. Probably related to the fact that it's running with all features turned on, including functions.

**Comment by matthewkrupnik** [comment]
Ok should be fixed now

**Comment by chrsin** [comment]
Latest image fixed the arm64 issue.

I am however getting the following when starting the image now (from the same compose file):
```
up to date, audited 775 packages in 1s

45 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
⚠  emulators: You are not currently authenticated so some features may not work correctly. Please run firebase login to authenticate the CLI.
i  emulators: Starting emulators: functions, firestore, pubsub
⚠  hub: Error when trying to check port 4400 on ::1: Error: listen EADDRNOTAVAIL: address not available ::1:4400
⚠  hub: Port 4400 is available on 127.0.0.1 but not ::1. This may cause issues with some clients.
⚠  hub: If you encounter connectivity issues, consider switching to a different port or explicitly specifying "host": "<ip address>" instead of hostname in firebase.json
⚠  logging: Error when trying to check port 4500 on ::1: Error: listen EADDRNOTAVAIL: address not available ::1:4500
⚠  logging: Port 4500 is available on 127.0.0.1 but not ::1. This may cause issues with some clients.
⚠  logging: If you encounter connectivity issues, consider switching to a different port or explicitly specifying "host": "<ip address>" instead of hostname in firebase.json
⚠  eventarc: Error when trying to check port 9299 on ::1: Error: listen EADDRNOTAVAIL: address not available ::1:9299
⚠  eventarc: Port 9299 is available on 127.0.0.1 but not ::1. This may cause issues with some clients.
⚠  eventarc: If you encounter connectivity issues, consider switching to a different port or explicitly specifying "host": "<ip address>" instead of hostname in firebase.json
⚠  functions: The following emulators are not running, calls to these services from the Functions emulator will affect production: auth, database, hosting, storage
✔  functions: Using node@16 from host.
⚠  functions: You are not signed in to the Firebase CLI. If you have authorized this machine using gcloud application-default credentials those may be discovered and used to access production services.
⚠  functions: Unable to fetch project Admin SDK configuration, Admin SDK behavior in Cloud Functions emulator may be incorrect.
i  firestore: Firestore Emulator logging to firestore-debug.log
✔  firestore: Firestore Emulator UI websocket is running on 5005.
i  pubsub: Pub/Sub Emulator logging to pubsub-debug.log
⚠  pubsub: Fatal error occurred: 
   Pub/Sub Emulator has exited with code: 134, 
   stopping all running emulators
i  functions: Stopping Functions Emulator
i  firestore: Stopping Firestore Emulator
i  pubsub: Stopping Pub/Sub Emulator
⚠  pubsub: Error stopping Pub/Sub Emulator
i  eventarc: Stopping Eventarc Emulator
i  hub: Stopping emulator hub
```
Did you change anything else? Or is there something that needs to change when not running on arm64?
Could be a server not responding i guesss. :/

**Comment by chrsin** [comment]
Might be this one: https://github.com/firebase/firebase-tools/issues/5256
Could be distro related.

**Comment by chrsin** [comment]
@matthewkrupnik is the image working for you now?

I've asked a couple of friends if they could run the image and everyone experience the same issue I've described above. (Even on Mac M1)

The firestore service definition in the docker-compose.yml is as follows:
```
  firestore_emulator:
    container_name: firestore
    image: matthewkrupnik/docker-firestore-emulator-with-ui:latest
    ports:
      - 8080:8080
      - 4000:4000
      - 8085:8085
      - 5001:5001
      - 5005:5005
    environment:
      - FIRESTORE_WS_PORT=5005
      - PORT=8080
```

**Comment by matthewkrupnik** [comment]
Does this affect you in any ways? It's just because it's trying to bind on IPv4 and IPv6 address, but since it's docker there is no IPv6 available. It does say that it's `available on 127.0.0.1` so it should work just fine.

There's a discussion about it here: https://github.com/firebase/firebase-tools/issues/3843
There are some work arounds, but latest version seem to not fail and just display a warning if IPv6 is not available.

**Comment by chrsin** [comment]
It's the:
```
⚠  pubsub: Fatal error occurred: 
   Pub/Sub Emulator has exited with code: 134, 
   stopping all running emulators
i  functions: Stopping Functions Emulator
i  firestore: Stopping Firestore Emulator
i  pubsub: Stopping Pub/Sub Emulator
⚠  pubsub: Error stopping Pub/Sub Emulator
i  eventarc: Stopping Eventarc Emulator
i  hub: Stopping emulator hub
```
Messages I am referring to.
The image is unusable basically unusable for me at this point since its just shutting it self down after trying to start.
Aren't you experiencing this?

Have you made sure to pull the latest image? (I'm not sure its pulling it unless you actually run "docker pull")

**Comment by matthewkrupnik** [comment]
I've been using my local build for testing. I checked the dockerhub image and I get same error. I switched it up from Alpine to Debian as the base image. Seems to be working for me now. Give it a go now and see if it stops crashing. If it's still crashing I'll add debug flag to entrypoint script so there's more logs about the error

**Comment by chrsin** [comment]
Just tested and it works!
Very nice!
The UI is just working aswell and all is good! I'm closing this good job. :)
