### ISSUE TITLE
ARM64 version?

### ISSUE THREAD

**Issue by rogeralsing** [matthewkrupnik/docker-firestore-emulator-with-ui#15]
Is there any chance that we might get an ARM64 compatible version?
Running the AMD64 image on a M1 Macbook works, but it is extremely slow to boot up. it takes several minutes before it becomes responsive

**Comment by matthewkrupnik** [comment]
Ran a multi-platform build targeting `amd64` and `arm64`.
Looks like it shows up correctly on dockerhub. Give it a go and let me know how it goes.
